

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "florian.recape@wanadoo.fr",
    "password": "toto@0208"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMxMjYyMjJ9.u8h8IjCshUrin0G68YqLLs17w3QmsgSI2UL-5jOz5DA"
}

###

GET http://localhost:4000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMxMjM4NDQsImV4cCI6MTY0MzEyMzg1OX0.V3zYJpFHepcUEG8K_dc04ryFmrsNzZCMIAcIBf52foc