

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "florian.recape@wanadoo.fr",
    "password": "toto@0208"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMxMjYyMjJ9.u8h8IjCshUrin0G68YqLLs17w3QmsgSI2UL-5jOz5DA"
}

###

GET http://localhost:3000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjA0NDcxODJkMTU1YTdkNWMzMjkxOCIsImlhdCI6MTY0MzMwNTMyMSwiZXhwIjoxNjQzMzA1NDQxfQ.O0FcnqyGsHdqWxutrlfJYoL6Uu7xlzmFnS5MMKrpw0w

###

GET http://localhost:3000/books
